  
# Cloud builder for the dotnet builder.

steps:
- name: 'gcr.io/cloud-builders/dotnet'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
        dotnet QuantConnect.Lean.sln

images:
- 'gcr.io/$PROJECT_ID/dotnet'
